#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f fetch.vcd

find ../rtl -type f -name "*.sv" > filelist.f

# run Verilator to translate Verilog into C++, including C++ testbench
verilator   -Wall -cc --trace \
            ../rtl/fetch/fetch_top.sv \
            --exe ./our_tests/fetch_tb.cpp \
            -f filelist.f \
            --top-module fetch_top \
            --prefix "Vdut" \
            -o Vdut -LDFLAGS "-lgtest -lgtest_main -lpthread"

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vdut.mk

# run executable simulation file
obj_dir/Vdut