#!/bin/sh

# cleanup
rm -rf obj_dir/
rm -rf test_out/f1_fsm/

find ../rtl -type f -name "*.sv" > filelist.f

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall -cc --trace ../rtl/top.sv --exe ./vbuddy_test/f1_fsm_tb.cpp -f filelist.f --prefix "Vdut"

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vdut.mk Vdut

# run executable simulation file
obj_dir/Vdut