../rtl/fetch/fetch_top.sv
../rtl/fetch/fetch_pipeline_regfile.sv
../rtl/fetch/pc_register.sv
../rtl/fetch/instr_mem.sv
../rtl/general-purpose/adder.sv
../rtl/general-purpose/mux3.sv
../rtl/general-purpose/mux.sv
../rtl/execute/branch_logic.sv
../rtl/execute/execute_top.sv
../rtl/execute/hazard_unit.sv
../rtl/execute/alu.sv
../rtl/execute/execute_pipeline_regfile.sv
../rtl/memwrite/memwrite_top.sv
../rtl/memwrite/memwrite_pipeline_regfile.sv
../rtl/memwrite/loadstore_parsing_unit.sv
../rtl/memwrite/data_mem.sv
../rtl/top-module-interfaces/interfaceW.sv
../rtl/top-module-interfaces/interfaceD.sv
../rtl/top-module-interfaces/interfaceM.sv
../rtl/top-module-interfaces/interfaceE.sv
../rtl/top.sv
../rtl/decode/control_unit.sv
../rtl/decode/decode_top.sv
../rtl/decode/sign_ext.sv
../rtl/decode/decode_pipeline_regfile.sv
../rtl/decode/register_file.sv
